export const Type: string[] = [
    "Planet",
    "Cluster",
    "Space station",
    "TV",
    "Resort",
    "Fantasy town",
    "Dream",
    "Dimension",
    "Unknown",
    "Microverse",
    "Menagerie",
    "Game",
    "Customs",
    "Daycare",
    "Miniverse",
    "Teenyverse",
    "Box",
    "Spacecraft",
    "Artificially generated world",
    "Machine",
    "Arcade",
    "Spa",
    "Quadrant",
    "Quasar",
    "Mount",
    "Liquid",
    "Convention",
    "Woods",
    "Diegesis",
    "Non-Diegetic Alternative Reality",
    "Nightmare",
    "Asteroid",
    "Acid Plant",
    "Reality",
    "Death Star",
    "Base",
    "Elemental Rings",
    "Human",
    "Space",
    "Hell",
    "Police Department",
    "Country",
    "Consciousness",
    "Memory"
]

export const Dimension: string[] = [
    "Replacement Dimension",
    "Unknown dimension",
    "Fantasy Dimension",
    "Fascist Teddy Bear Dimension",
    "Wasp Dimension",
    "Tusk Dimension",
    "Magic Dimension",
    "Dimension D716-C",
    "Dimension J-22",
    "Unknown",
    "Dimension C-35",
    "Dimension C-137",
    "Pizza Dimension",
    "Phone Dimension",
    "Chair Dimension",
    "Fascist Dimension",
    "Fascist Shrimp Dimension",
    "Giant Telepathic Spiders Dimension",
    "Dimension K-22",
    "Dimension D-99",
    "Dimension D716",
    "Dimension D716-B",
    "Testicle Monster Dimension",
    "Cromulon Dimension",
    "Dimension C-500A",
    "Dimension K-83",
    "Dimension J19ζ7",
    "Eric Stoltz Mask Dimension",
    "Evil Rick's Target Dimension",
    "Post-Apocalyptic Dimension",
    "Cronenberg Dimension",
    "Dimension 5-126",
]